products:
  - name: "Tissue 2 tone Saree"
    price: "2500"
    discounted_price: "1299"   # Optional: if provided, JS computes discount percent.
    discount_percent: ""            # Alternatively, set e.g. "10" for 
    payment_options: "COD, Google Pay, UPI"
    sizes: "Free Size"
    description: "A stunning Kanjivaram silk saree with rich colors and intricate zari work."
    images: "2TON1.jpg, ton3.jpg, ton4.jpg, ton5.jpg"

