products:
  - name: "Kanjivaram Silk Saree"
    price: "149.99"
    discounted_price: "134.99"      # Optional: if provided, JS computes discount percent.
    discount_percent: ""            # Alternatively, set e.g. "10" for 10%
    payment_options: "COD, Google Pay, UPI"
    sizes: "S, M, L, XL"
    description: "A stunning Kanjivaram silk saree with rich colors and intricate zari work."
    images: "saree/1.jpg, saree/2.jpg, saree/3.jpg, saree/4.jpg, saree/5.jpg, saree/6.jpg"

  - name: "Banarasi Brocade Saree"
    price: "139.99"
    discounted_price: "125.99"
    discount_percent: ""
    payment_options: "COD, Google Pay, UPI"
    sizes: "S, M, L, XL"
    description: "Elegant Banarasi brocade saree with elaborate motifs and a luxurious feel. A perfect choice for festive celebrations."
    images: "saree/1.jpg, saree/2.jpg, saree/3.jpg, saree/4.jpg, saree/5.jpg, saree/6.jpg"

  - name: "Chiffon Printed Saree"
    price: "69.99"
    discounted_price: ""
    discount_percent: ""
    payment_options: "COD, Google Pay, UPI"
    sizes: "S, M, L, XL"
    description: "Lightweight chiffon saree with vibrant prints, ideal for summer outings. Easy to drape and comfortable to wear."
    images: "saree/1.jpg, saree/2.jpg, saree/3.jpg, saree/4.jpg, saree/5.jpg, saree/6.jpg"

  - name: "Georgette Embroidered Saree"
    price: "89.99"
    discounted_price: ""
    discount_percent: ""
    payment_options: "COD, Google Pay, UPI"
    sizes: "S, M, L, XL"
    description: "Beautiful georgette saree featuring intricate embroidery. Perfect for evening events and parties."
    images: "saree/1.jpg, saree/2.jpg, saree/3.jpg, saree/4.jpg, saree/5.jpg, saree/6.jpg"

  - name: "Cotton Handloom Saree"
    price: "49.99"
    discounted_price: ""
    discount_percent: ""
    payment_options: "COD, Google Pay, UPI"
    sizes: "S, M, L, XL"
    description: "Soft and breathable handloom cotton saree, perfect for daily wear. A blend of comfort and traditional elegance."
    images: "saree/1.jpg, saree/2.jpg, saree/3.jpg, saree/4.jpg, saree/5.jpg, saree/6.jpg"

  - name: "Net Lace Saree"
    price: "99.99"
    discounted_price: ""
    discount_percent: ""
    payment_options: "COD, Google Pay, UPI"
    sizes: "S, M, L, XL"
    description: "Stylish net lace saree adorned with delicate lace work. Ideal for cocktail parties and evening gatherings."
    images: "saree/1.jpg, saree/2.jpg, saree/3.jpg, saree/4.jpg, saree/5.jpg, saree/6.jpg"

  - name: "Satin Saree with Sequin Work"
    price: "119.99"
    discounted_price: ""
    discount_percent: ""
    payment_options: "COD, Google Pay, UPI"
    sizes: "S, M, L, XL"
    description: "Luxurious satin saree embellished with sequins for a glamorous look. Perfect for festive occasions and celebrations."
    images: "saree/1.jpg, saree/2.jpg, saree/3.jpg, saree/4.jpg, saree/5.jpg, saree/6.jpg"
